# Generated by Django 4.0.7 on 2024-10-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('responder', 'Responder'), ('civilian', 'Civilian')], default='civilian', max_length=9),
        ),
    ]
