# Generated by Django 4.0.7 on 2024-10-19 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.TextField(default='davie', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='33324', help_text='Please use the xxx-xxx-xxxx format.', max_length=12, validators=[django.core.validators.RegexValidator('\\d{3}-\\d{3}-\\d{4}', 'Please enter a valid phone number in the xxx-xxx-xxxx format.')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='street_address',
            field=models.TextField(default='1234 Home Ave', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='zip_code',
            field=models.IntegerField(default='33332', max_length=5),
            preserve_default=False,
        ),
    ]
