# Generated by Django 4.0.7 on 2024-10-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_city_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='zip_code',
            field=models.TextField(max_length=5),
        ),
    ]
