# Generated by Django 4.0.7 on 2024-10-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(default='now', upload_to='profile_photos/'),
            preserve_default=False,
        ),
    ]
