# Generated by Django 4.0.7 on 2024-10-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_companions_profilepage_companion_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('relationship_type', models.CharField(choices=[('select option', 'Select Option'), ('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('in-law', 'In-Law'), ('friend', 'Friend'), ('neighbor', 'Neighbor')], default='select option', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Companions',
        ),
        migrations.AlterField(
            model_name='profilepage',
            name='companion_list',
            field=models.ManyToManyField(related_name='companions', to='profile_app.companion'),
        ),
    ]
