# Generated by Django 4.0.7 on 2024-10-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_companion_delete_companions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='relationship_type',
            field=models.CharField(choices=[('select option', 'Select Option'), ('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('in-law', 'In-Law'), ('friend', 'Friend'), ('neighbor', 'Neighbor')], default='select option', max_length=30),
        ),
    ]
