# Generated by Django 4.0.7 on 2024-10-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0010_alter_companion_relationship_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companion',
            name='profile_photo',
        ),
        migrations.AlterField(
            model_name='companion',
            name='relationship_type',
            field=models.CharField(choices=[('select_option', 'Select Option'), ('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('in-law', 'In-Law'), ('friend', 'Friend'), ('neighbor', 'Neighbor')], default='select_option', max_length=30),
        ),
    ]
