# Generated by Django 4.0.7 on 2024-10-19 08:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_remove_alert_created_at_remove_alert_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.TextField()),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_updates', to='alerts.alert')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
