# Generated by Django 4.0.7 on 2024-10-19 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alertupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-modified', '-created']},
        ),
    ]
