# Generated by Django 4.0.7 on 2024-10-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alter_alertupdate_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='affected_zip_code',
            field=models.ManyToManyField(blank=True, related_name='alerts', to='alerts.zipcode'),
        ),
    ]
