# Generated by Django 4.0.7 on 2024-10-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_zipcode_alert_affected_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='affected_zip_code',
            field=models.ManyToManyField(related_name='alert_zip_codes', to='alerts.zipcode'),
        ),
    ]
